/*		UDP Packet forwarder for internet connected HIL
 *
 * 		File:				widgets.h
 * 		Author(s): 			16 May 2018
 * 		Creation Date:		P L Evans
 *
 * 		Description:
 *		List of GUI widgets
 *
 */

#ifndef WIDGETS_H
#define WIDGETS_H

enum {
	WIDGET_MAINWINDOW = 0,
	WIDGET_TEXTOUT,
	WIDGET_TEXTOUTPORT,

	WIDGET_LOCALPORT,
	
	WIDGET_HILIP,
	WIDGET_HILPORT,

	WIDGET_RECVVALUE1,
	WIDGET_RECVVALUE2,
	WIDGET_RECVVALUE3,
	WIDGET_RECVVALUE4,
	WIDGET_RECVVALUE5,
	WIDGET_RECVVALUE6,
	WIDGET_RECVVALUE7,
	WIDGET_RECVVALUE8,
	WIDGET_RECVVALUE9,
	WIDGET_RECVVALUE10,
	WIDGET_RECVVALUE11,
	WIDGET_RECVVALUE12,
	WIDGET_RECVVALUE13,
	WIDGET_RECVVALUE14,
	WIDGET_RECVVALUE15,
	WIDGET_RECVVALUE16,
	WIDGET_RECVVALUE17,
	WIDGET_RECVVALUE18,

	WIDGET_SENDVALUE1,
	WIDGET_SENDVALUE2,
	WIDGET_SENDVALUE3,
	WIDGET_SENDVALUE4,
	WIDGET_SENDVALUE5,
	WIDGET_SENDVALUE6,
	WIDGET_SENDVALUE7,
	WIDGET_SENDVALUE8,
	WIDGET_SENDVALUE9,
	WIDGET_SENDVALUE10,
	WIDGET_SENDVALUE11,
	WIDGET_SENDVALUE12,
	WIDGET_SENDVALUE13,
	WIDGET_SENDVALUE14,
	WIDGET_SENDVALUE15,
	WIDGET_SENDVALUE16,
	WIDGET_SENDVALUE17,
	WIDGET_SENDVALUE18,

	WIDGET_REMOTELIST,
	WIDGET_REMOTESTORE,
	WIDGET_ADDREMOTE,
	WIDGET_REMOVEREMOTE,

	WIDGET_EMULATEREMOTE,
	WIDGET_EMULATEFREQUENCY,

	WIDGET_BROADCASTMESSAGE,
	WIDGET_BROADCASTBUTTON,

	WIDGET_MENULOCALSTART,
	WIDGET_MENULOCALSTOP,
	WIDGET_MENUREMOTESTART,
	WIDGET_MENUREMOTESTOP,

	WIDGET_NUMBER
};


#endif
