

#ifndef WIDGETS_H
#define WIDGETS_H

enum {
	WIDGET_MAINWINDOW = 0,
	WIDGET_TEXTOUT,
	WIDGET_TEXTOUTPORT,

	WIDGET_LOCALPORT,
	
	WIDGET_HILIP,
	WIDGET_HILPORT,

	WIDGET_PARAMNAME1,
	WIDGET_PARAMNAME2,
	WIDGET_PARAMNAME3,
	WIDGET_PARAMNAME4,
	WIDGET_PARAMNAME5,
	WIDGET_PARAMNAME6,
	WIDGET_PARAMNAME7,
	WIDGET_PARAMNAME8,
	WIDGET_PARAMNAME9,
	WIDGET_PARAMNAME10,
	WIDGET_PARAMNAME11,
	WIDGET_PARAMNAME12,
	WIDGET_PARAMNAME13,
	WIDGET_PARAMNAME14,
	WIDGET_PARAMNAME15,
	WIDGET_PARAMNAME16,
	WIDGET_PARAMNAME17,
	WIDGET_PARAMNAME18,

	WIDGET_PARAMVALUE1,
	WIDGET_PARAMVALUE2,
	WIDGET_PARAMVALUE3,
	WIDGET_PARAMVALUE4,
	WIDGET_PARAMVALUE5,
	WIDGET_PARAMVALUE6,
	WIDGET_PARAMVALUE7,
	WIDGET_PARAMVALUE8,
	WIDGET_PARAMVALUE9,
	WIDGET_PARAMVALUE10,
	WIDGET_PARAMVALUE11,
	WIDGET_PARAMVALUE12,
	WIDGET_PARAMVALUE13,
	WIDGET_PARAMVALUE14,
	WIDGET_PARAMVALUE15,
	WIDGET_PARAMVALUE16,
	WIDGET_PARAMVALUE17,
	WIDGET_PARAMVALUE18,

	WIDGET_REMOTELIST,
	WIDGET_REMOTESTORE,
	WIDGET_ADDREMOTE,
	WIDGET_REMOVEREMOTE,

	WIDGET_EMULATEREMOTE,
	WIDGET_EMULATEFREQUENCY,

	WIDGET_BROADCASTMESSAGE,
	WIDGET_BROADCASTBUTTON,

	WIDGET_MENULOCALSTART,
	WIDGET_MENULOCALSTOP,
	WIDGET_MENUREMOTESTART,
	WIDGET_MENUREMOTESTOP,

	WIDGET_NUMBER
};


#endif
