/*		UDP Packet forwarder for internet connected HIL
 *
 * 		File:				widgets.h
 * 		Author(s): 			16 May 2018
 * 		Creation Date:		P L Evans
 *
 * 		Description:
 *		List of GUI widgets
 *
 */

#ifndef WIDGETS_H
#define WIDGETS_H

enum {
	WIDGET_MAINWINDOW = 0,
	WIDGET_TEXTOUT,
	WIDGET_TEXTOUTPORT,

	WIDGET_LOCALPORT,
	
	WIDGET_INTERNETPORT,

	WIDGET_HILIP,
	WIDGET_HILPORT,

	WIDGET_RECVVALUE1,
	WIDGET_RECVVALUE2,
	WIDGET_RECVVALUE3,
	WIDGET_RECVVALUE4,
	WIDGET_RECVVALUE5,
	WIDGET_RECVVALUE6,
	WIDGET_RECVVALUE7,
	WIDGET_RECVVALUE8,
	WIDGET_RECVVALUE9,

	WIDGET_RECVNAME1,
	WIDGET_RECVNAME2,
	WIDGET_RECVNAME3,
	WIDGET_RECVNAME4,
	WIDGET_RECVNAME5,
	WIDGET_RECVNAME6,
	WIDGET_RECVNAME7,
	WIDGET_RECVNAME8,
	WIDGET_RECVNAME9,

	WIDGET_RECVTS1,
	WIDGET_RECVTS2,
	WIDGET_RECVTS3,
	WIDGET_RECVTS4,
	WIDGET_RECVTS5,
	WIDGET_RECVTS6,
	WIDGET_RECVTS7,
	WIDGET_RECVTS8,
	WIDGET_RECVTS9,

	WIDGET_SENDVALUE1,
	WIDGET_SENDVALUE2,
	WIDGET_SENDVALUE3,
	WIDGET_SENDVALUE4,
	WIDGET_SENDVALUE5,
	WIDGET_SENDVALUE6,
	WIDGET_SENDVALUE7,
	WIDGET_SENDVALUE8,
	WIDGET_SENDVALUE9,

	WIDGET_SENDNAME1,
	WIDGET_SENDNAME2,
	WIDGET_SENDNAME3,
	WIDGET_SENDNAME4,
	WIDGET_SENDNAME5,
	WIDGET_SENDNAME6,
	WIDGET_SENDNAME7,
	WIDGET_SENDNAME8,
	WIDGET_SENDNAME9,

	WIDGET_SENDTS1,
	WIDGET_SENDTS2,
	WIDGET_SENDTS3,
	WIDGET_SENDTS4,
	WIDGET_SENDTS5,
	WIDGET_SENDTS6,
	WIDGET_SENDTS7,
	WIDGET_SENDTS8,
	WIDGET_SENDTS9,

	WIDGET_REMOTELIST,
	WIDGET_REMOTESTORE,
	WIDGET_ADDREMOTE,
	WIDGET_REMOVEREMOTE,
	WIDGET_REMOTEIP,
	WIDGET_REMOTEPORT,

	WIDGET_BROADCASTBUTTON,
	WIDGET_BROADCASTTS,
	WIDGET_BROADCASTID1,
	WIDGET_BROADCASTID2,
	WIDGET_BROADCASTID3,
	WIDGET_BROADCASTID4,
	WIDGET_BROADCASTID5,
	WIDGET_BROADCASTID6,
	WIDGET_BROADCASTID7,
	WIDGET_BROADCASTID8,
	WIDGET_BROADCASTID9,
	WIDGET_BROADCASTVALUE1,
	WIDGET_BROADCASTVALUE2,
	WIDGET_BROADCASTVALUE3,
	WIDGET_BROADCASTVALUE4,
	WIDGET_BROADCASTVALUE5,
	WIDGET_BROADCASTVALUE6,
	WIDGET_BROADCASTVALUE7,
	WIDGET_BROADCASTVALUE8,
	WIDGET_BROADCASTVALUE9,

	WIDGET_MENULOCALSTART,
	WIDGET_MENULOCALSTOP,
	WIDGET_MENUREMOTESTART,
	WIDGET_MENUREMOTESTOP,

	WIDGET_NUMBER
};


#endif
